name: Deploy React app to EC2 instance

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Initialize environment
      run: |
        cp .env.development .env
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Zip build files
      run: zip -r build.zip build/
      
    - name: Install AWS CLI S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Upload Archive to S3
      run: |
        aws s3 cp build.zip s3://rangon-bucket/build.zip
        
    - name: Download Archive from S3 to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ${{ secrets.EC2_INSTANCE_USERNAME }}
        key: ${{ secrets.EC2_INSTANCE_KEY }}
        source: build.zip
        target: /var/www/dev/frontend/main/temp/
    
    - name: Remove Old Archive Files From Development and Testing
      run: | 
        rm -rf /var/www/dev/frontend/main/build/*
        rm -rf /var/www/testing/frontend/main/build/*

    - name: Unzip Archive to Development and Testing
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ${{ secrets.EC2_INSTANCE_USERNAME }}
        key: ${{ secrets.EC2_INSTANCE_KEY }}
        script: |
          sudo unzip -o /var/www/dev/frontend/main/temp/build.zip -d /var/www/dev/frontend/main/
          sudo unzip -o /var/www/dev/frontend/main/temp/build.zip -d /var/www/testing/frontend/main/
          sudo rm -rf build.zip
