name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 16.x to Build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build app
        run: npm run build

      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: LMS-FE
          path: build

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: LMS-FE
          path: build

      - name: Declare EC2 Key
        run: |
          declare -r filename="$(%Y_%m_%d_%H_%M_%S)"
        shell: bash
        env: 
          AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}
      
      - name: Copy Artifact to EC2
        run: |
          chmod 400 key.pem
          scp -v -r -i key.pem build/ ubuntu@ec2-54-255-209-186.ap-southeast-1.compute.amazonaws.com:/var/www/lms-frontend/